webui/blueprints/device.py
"""

    NFC controlled door access.
    Copyright (C) 2015  Yatekii yatekii(at)yatekii.ch

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""


from flask import flash
from flask import render_template
from flask import url_for
from flask import redirect
from flask import request


from flask import Blueprint
from sqlalchemy import and_


import helpers
import models
from webui.wrappers import check_session, check_rights
from webui.permission_flags import *

blueprint = Blueprint('device', __name__, template_folder='templates')


@blueprint.route('/view/', defaults={'id': '0'})
@blueprint.route('/view/<id>/', methods=['POST', 'GET'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def view(sqlsession, id):
    id = int(id)
    active = 'devices'
    device = None
    if id > 0:
        device = sqlsession.query(models.Device).filter_by(id=id).first()
    devices = sqlsession.query(models.Device).filter_by().all()
    s = sqlsession.query(models.Service).filter_by().all()
    services = []
    for service in s:
        services.append((service, device in service.devices))

    return render_template(
        'device.html',
        active=active,
        date=helpers.today(),
        id=id,
        device=device,
        devices=devices,
        services=services,
        previous=dict(request.args.items(multi=False))
    )


@blueprint.route('/add', methods=['POST'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def add(sqlsession):
    error = False

    if not error:
        device = models.Device(
            name=request.form['add_device_name'],
            pubkey=request.form['add_device_pubkey'],
            creation_date=helpers.today(),
            is_online=False,
            is_enabled=True
        )
        sqlsession.add(device)
        sqlsession.commit()
        flash('New device was created successfully', 'success')
        return redirect(url_for('device.view', id=device.id))

    else:
        return redirect(url_for(
            'device.view',
            device_name=request.form['add_device_name'],
            device_pubkey=request.form['add_device_pubkey']
        ))


@blueprint.route('/remove', methods=['POST'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def remove(sqlsession):
    device = sqlsession.query(models.Device).filter_by(id=request.form['device_id']).first()

    if device:
        sqlsession.delete(device)
        flash('Device with id %s was successfully removed.' % request.form['device_id'], 'success')

    else:
        flash('Device with id %s was not found.' % request.form['device_id'], 'danger')

    return redirect(url_for('device.view'))


@blueprint.route('/change', methods=['POST'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def change(sqlsession):
    error = False
    device = sqlsession.query(models.Device).filter_by(id=request.form.get('change_device_id')).first()

    if not device:
        error = True
        flash('Device with id %s was not found.' % request.form['change_device_id'], 'danger')

    if device.is_online:
        error = True
        flash('Device with id %s is still online. Please make sure it\'s offline to make changes.'
              % request.form['change_device_id'], 'danger')

    if not error:
        device.name = request.form['change_device_name']
        device.pubkey = request.form['change_device_pubkey']
        flash('Device with id %d has been changed.' % device.id, 'success')

    return redirect(url_for('device.view', id=device.id))

@blueprint.route('/revoke', methods=['POST'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def revoke(sqlsession):
    error = False
    device = sqlsession.query(models.Device).filter_by(id=int(request.form.get('change_device_id'))).first()
    if not device:
        error = True
        flash('Device with id %s was not found.' % request.form['change_device_id'], 'danger')

    if not error:
        error, errors = models.Device.revoke(device.id)
        if error:
            for e in errors:
                flash(e[1], 'danger')
        else:
            device.is_enabled = False
            flash('Device with id %d has been revoked.' % device.id, 'success')

    return redirect(url_for('device.view', id=device.id))

@blueprint.route('/enable', methods=['POST'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def enable(sqlsession):
    error = False
    device = sqlsession.query(models.Device).filter_by(id=request.form.get('change_device_id')).first()

    if not device:
        error = True
        flash('Device with id %s was not found.' % request.form['change_device_id'], 'danger')

    if not error:
        device.is_enabled = True
        flash('Device with id %d has been enabled.' % device.id, 'success')

    return redirect(url_for('device.view', id=device.id))


@blueprint.route('/change_service', methods=['POST'])
@check_session()
@check_rights(OVER_NINETHOUSAND | MANIPULATE_DEVICES)
@helpers.handle_dbsession()
def change_service(sqlsession):
    error = False
    device = sqlsession.query(models.Device).filter_by(id=request.form.get('device_id')).first()
    service = sqlsession.query(models.Service).filter_by(id=request.form.get('service_id')).first()


    if not device:
        error = True
        flash('Device with id %s was not found.' % request.form['device_id'], 'danger')

    if not service:
        error = True
        flash('Service with id %s was not found.' % request.form['service_id'], 'danger')

    if not error:
        if request.form.get('add_service'):
            if service not in device.services:
                device.services.append(service)
                users = sqlsession.query(models.User).filter(
                    and_(
                        ~models.User.data.any(service=service),
                        models.User.tokens.any(models.Token.devices.any(models.Device.services.contains(service)))
                    )
                ).all()
                print(users)
                for user in users:
                    if user.data is None:
                        user.data = []
                    for field in service.fields:
                        user.data.append(models.ServiceData(key=field.key, user=user, device=device, service=service))
                flash('Service %s has been added to device %s.' % (service.name, device.name), 'success')
            else:
                flash('Service is already activated. No need to activate it.', 'danger')

        elif request.form.get('remove_service'):
            if service in device.services:
                device.services.remove(service)
                flash('Service %s has been removed from device %s.' % (service.name, device.name), 'success')
            else:
                flash('Service is not activated. No need to remove it.', 'danger')

        elif request.form.get('purge_service'):
            sqlsession.query(models.ServiceData).filter_by(service=service).delete()
            flash('Data for service %s has been purged.' % service.name, 'success')

    return redirect(url_for('device.view', id=device.id))

webui/blueprints/profile.py
"""

    NFC controlled door access.
    Copyright (C) 2015  Yatekii yatekii(at)yatekii.ch

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""


from flask import flash
from flask import render_template
from flask import url_for
from flask import redirect
from flask import request
from flask import session
from flask import Blueprint


import helpers
import models
from webui.wrappers import check_session


blueprint = Blueprint('profile', __name__, template_folder='templates')


@blueprint.route('/general', methods=['POST', 'GET'])
@check_session()
@helpers.handle_dbsession()
def general(sqlsession):
    active = 'profile'

    user = sqlsession.query(models.User).filter_by(username=session['username']).first()

    return render_template(
        'profile_general.html',
        active=active,
        category='general',
        user=user
    )

@blueprint.route('/password', methods=['POST', 'GET'])
@check_session()
@helpers.handle_dbsession()
def password(sqlsession):
    active = 'profile'

    user = sqlsession.query(models.User).filter_by(username=session['username']).first()

    return render_template(
        'profile_password.html',
        active=active,
        category='password',
        user=user
    )


@blueprint.route('/settings', methods=['POST', 'GET'])
@check_session()
@helpers.handle_dbsession()
def settings(sqlsession):
    active = 'profile'

    user = sqlsession.query(models.User).filter_by(username=session['username']).first()

    devices = sqlsession.query(models.Device).all()

    return render_template(
        'profile_settings.html',
        active=active,
        category='settings',
        user=user,
        devices=devices
    )


@blueprint.route('/tokens', methods=['POST', 'GET'])
@check_session()
@helpers.handle_dbsession()
def tokens(sqlsession):
    active = 'profile'

    user = sqlsession.query(models.User).filter_by(username=session['username']).first()

    return render_template(
        'profile_tokens.html',
        active=active,
        category='tokens',
        user=user,
        date=helpers.today()
    )


@blueprint.route('/change_settings', methods=['POST'])
@check_session()
@helpers.handle_dbsession()
def change_settings(sqlsession):
    error = False
    user = sqlsession.query(models.User).filter_by(id=request.form.get('change_user_id')).first()

    if not user:
        error = True
        flash('User with id %s was not found.' % request.form.get('change_user_id'), 'danger')

    device = sqlsession.query(models.Device).filter_by(id=request.form.get('change_user_device_id')).first()

    if not device:
        # if 0 != int(request.form.get('change_user_device_id')):
        #     device = None
        error = True
        flash('Device with id %s was not found.' % request.form.get('change_user_device_id'), 'danger')

    if not error:
        user.default_device = device
        flash('User %s has been changed.' % (user.name), 'success')

    return redirect(url_for('profile.settings'))

webui/blueprints/search.py
"""

    NFC controlled door access.
    Copyright (C) 2015  Yatekii yatekii(at)yatekii.ch

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""


from flask import render_template
from flask import request
from flask import Blueprint


import helpers
import models


from webui.wrappers import check_session
from sqlalchemy import or_


blueprint = Blueprint('search', __name__, template_folder='templates')


@blueprint.route('/', defaults={'type' : 'list', 'id': '0'})
@blueprint.route('/<type>/<id>/', methods=['POST', 'GET'])
@check_session()
@helpers.handle_dbsession()
def search(sqlsession, type, id):
    id = int(id)
    active = 'search'

    user = None
    if id > 0:
        user = sqlsession.query(models.User).filter_by(id=int(id)).first()

    device = None
    if id > 0:
        device = sqlsession.query(models.Device).filter_by(id=id).first()

    users = sqlsession.query(models.User).filter(
        or_(
            models.User.name.like('%' + request.args.get('q') + '%'),
            models.User.username.like('%' + request.args.get('q') + '%'))
        ).all()
    devices = sqlsession.query(models.Device).filter(
            models.Device.name.like('%' + request.args.get('q') + '%')
        ).all()
    return render_template(
        'search.html',
        active=active,
        date=helpers.today(),
        id=id,
        q=request.args.get('q'),
        type=type,
        user=user,
        users=users,
        device=device,
        devices=devices
    )

webui/blueprints/service.py
"""

    NFC controlled door access.
    Copyright (C) 2015  Yatekii yatekii(at)yatekii.ch

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as
    published by the Free Software Foundation, either version 3 of the
    License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""


from flask import flash
from flask import render_template
from flask import url_for
from flask import redirect
from flask import request
from flask import Blueprint


import helpers
import models
from webui.wrappers import check_session, check_rights
from webui.permission_flags import *

blueprint = Blueprint('service', __name__, template_folder='templates')


@blueprint.route('/view', defaults={'id': '0'})
@blueprint.route('/view/<id>/', methods=['POST', 'GET'])
@check_session()
@check_rights(0)
@helpers.handle_dbsession()
def view(sqlsession, id):
    active = 'service'
    id = int(id)

    services = sqlsession.query(models.Service).filter_by(uses_blueprint=True).order_by(models.Service.name.asc()).all()
    service = sqlsession.query(models.Service).filter_by(id=id).first()
    return render_template(
        'service.html',
        active=active,
        date=helpers.today(),
        id=id,
        service=service,
        services=services,
        previous=dict(request.args.items(multi=False))
    )

webui/templates/add_token.html
<form action="{{ url_for('token.add') }}" method=post>
    <h4>New Token</h4>
    <table class="table table-hover table_general">
        <tr>
            <td>ID</td>
            <td>{{ token.id }}</td>
        </tr>
        <tr>
            <td>Owner</td>
            <td>
                <span class="user_typeahead">
                    <input type="text" name="add_token_owner" class="typeahead form-control user_typeahead_name" title="Token owner" value="{{ previous['token_owner_name'] }}" />
                    <input type="text" name="add_token_owner_id" class="invisible user_typeahead_id" title="" value="{{ previous['token_owner_id'] }}" />
                </span>
            </td>
        </tr>
        <tr>
            <td>Expiry Date</td>
            <td>
                <input type="text" name="add_token_expiry_date" class="form-control" title="Token expiry date" value="{{ previous['token_expiry_date'] }}" />
            </td>
        </tr>
        <tr>
            <td>Creation Date</td>
            <td>{{ date }}</td>
        </tr>
        <tr>
            <td>Create?</td>
            <td>
                <input type="submit" class="form-control btn btn-success" value="Create" />
            </td>
        </tr>
    </table>
    <script type="text/javascript">

        init_edit_field('.button_change_token_expiry_date');

        remove_init();

        flashed_init();

        user_typeahead();
        device_typeahead();
    </script>
</form>

webui/templates/device.html
{% extends "layout_admin.html" %}

{% block navi %}
    {% include "list_devices.html" %}
{% endblock %}

{% block body %}
    {% if id == 0 %}
        {% include "add_device.html" %}
    {% else %}
        {% include "edit_device.html" %}
    {% endif %}
{% endblock %}

webui/templates/edit_device.html
<h4>
    {{ device.name }}
    {% if device.is_online %}
        <span style="color: green">[ONLINE]</span>
    {% else %}
        <span style="color: red">[OFFLINE]</span>
    {% endif %}
</h4>
<form class="change_device_name" action="{{ url_for('device.change', id=device.id) }}" method=post>
<table class="table table-hover table_general">
    <tr>
        <td>ID</td>
        <td>{{ device.id }}</td>
    </tr>
    <tr>
        <td>Name</td>
        <td>
            <input type="text" name="change_device_name" class="form-control" title="device owner" value="{{ device.name }}"/>
        </td>
    </tr>
    <tr>
        <td>Pubkey</td>
        <td>
            <input type="text" name="change_device_pubkey" class="form-control" title="device owner" value="{{ device.pubkey }}" />
            <input type="text" name="change_device_id" class="invisible" title="" value="{{ device.id }}" />
        </td>
    </tr>
    <tr>
        <td>Creation Date</td>
        <td>{{ device.creation_date }}</td>
    </tr>
    <tr>
        <td>
            Change?
        </td>
        <td>
            <input type="submit" class="form-control btn btn-success" value="Change" {% if device.is_online %}disabled{% endif %} />
        </td>
    </tr>
</table>
</form>
<table class="table table-hover table_general">
    <tr>
        <td colspan="2">
            <form class="remove_form col-lg-4" action="{{ url_for('device.change_service') }}" method=post>
                <select name="service_id" class="form-control button_float_left">
                    {% for service in services %}
                        <option value="{{ service[0].id }}">{{ service[0].name }}{% if service[1] %} *{% endif %}</option>
                    {% endfor %}
                </select>
                <input type="submit" name="add_service" class="form-control btn btn-danger col-lg-4" value="Add Service" {% if device.is_online %}disabled{% endif %} />
                <input type="submit" name="remove_service" class="form-control btn btn-danger col-lg-4" value="Remove Service" {% if device.is_online %}disabled{% endif %} />
                <input type="submit" name="purge_service" class="form-control btn btn-danger col-lg-4" value="Purge Service" {% if device.is_online %}disabled{% endif %} />
                <input name="device_id" class="invisible" value="{{ device.id }}" title="device id"/>
            </form>
        </td>
    </tr>
</table>
<table class="table table-hover table_general">
    <tr>
        <td colspan="2">
            <form class="remove_form button_float_left" action="{{ url_for('device.remove') }}" method=post>
                <input type="submit" class="form-control btn btn-danger" value="Remove" {% if device.is_online %}disabled{% endif %} />
                <input name="device_id" class="invisible" value="{{ device.id }}" title="device id"/>
            </form>
            {% if device.is_enabled %}
                <form class="revoke_form button_float_left" action="{{ url_for('device.revoke') }}" method=post>
                    <input type="submit" class="btn btn-default btn-warning" value="Revoke" />
                    <input name="change_device_id" class="invisible" value="{{ device.id }}" title="device id"/>
                </form>
            {% else %}
                <form class="activation_form button_float_left" action="{{ url_for('device.enable') }}" method=post>
                    <input type="submit" class="btn btn-default btn-success" value="Enable" />
                    <input name="change_device_id" class="invisible" value="{{ device.id }}" title="device id"/>
                </form>
            {% endif %}
        </td>
    </tr>
</table>
<h4>Tokens</h4>
<table class="table table-hover table_general">
    <tr>
        <td colspan="2">
            {%  for token in device.tokens %}
                <form style="float: left; margin-right: 10px" action="{{ url_for('token.remove_link_to_device') }}" method="POST">
                    <div class="btn-group" role="group" aria-label="..." style="float: left">
                        <button type="button" class="btn btn-default" onclick="window.location.href='{{ url_for('token.view', id=token.id) }}'">{{ token.id }}</button>
                        <button type="submit" class="btn btn-default"><span class="glyphicon-minus"></span></button>
                    </div>
                <input type="text" name="remove_link_token_to_device_device_id" class="invisible" value="{{ device.id }}">
                <input type="text" name="remove_link_token_to_device_token_id" class="invisible" value="{{ token.id }}">
                </form>
            {% endfor %}
        </td>
    </tr>
</table>
<script type="text/javascript">

    init_edit_field('.button_change_token_expiry_date');

    remove_init();

    flashed_init();

    user_typeahead();
    device_typeahead();
</script>

webui/templates/layout.html
<!doctype html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Yatekii">

    <link rel="icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='style.css') }}">
    <link rel=stylesheet type=text/css href="{{ url_for('static', filename='sites.css') }}">

    <script src="{{ url_for('static', filename='jquery-1.11.2.js') }}"></script>
    <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='typeahead.bundle.js') }}"></script>
    <script src="{{ url_for('static', filename='backdoor.js') }}"></script>

    <title>Backdoor</title>
</head>
<body>

<!-- NAVIGATION -->

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('home') }}">Backdoor</a>
            <a class="navbar-brand" style="float: left;" href="{{ url_for('control.open') }}"><span class="glyphicon glyphicon-log-in"></span></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <form method="GET" action="{{ url_for('search.search') }}" class="navbar-form navbar-right">
                <input class="form-control search_typeahead" placeholder="Search..." type="text" name="q">
            </form>
            <ul class="nav navbar-nav navbar-right">
            {% if session['id'] is defined %}
                <li {% if active == 'users' %} class="active" {% endif %}><a href="{{ url_for('user.view') }}">Users</a></li>
                <li {% if active == 'tokens' %} class="active" {% endif %}><a href="{{ url_for('token.view') }}">Tokens</a></li>
                <li {% if active == 'devices' %} class="active" {% endif %}><a href="{{ url_for('device.view') }}">Devices</a></li>
                <li {% if active == 'logs' %} class="active" {% endif %}><a href="#">Logs(soonTM)</a></li>
                <li {% if active == 'settings' %} class="active" {% endif %}><a href="{{ url_for('settings.general') }}">Settings</a></li>
                <li {% if active == 'profile' %} class="active" {% endif %}><a href="{{ url_for('profile.general') }}">Profile</a></li>
                <li {% if active == 'service' %} class="active" {% endif %}><a href="{{ url_for('service.view') }}">Services</a></li>
                <li><a href="{{ url_for('authentication.logout') }}">Logout</a></li>
            {% else %}
                <li><a href="{{ url_for('authentication.login') }}">Login</a></li>
            {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- CONTENT -->

<div class="container-fluid">
    <div class="row">
        {% block content %}{% endblock %}
    </div>

    <!-- FOOTER -->

    <hr />
    <footer>
        <p>(c)Bastli 2015</p>
    </footer>

</div>
<script type="text/javascript">
    search_typeahead();
</script>


</body>

webui/templates/list_devices.html
{% if active != 'search' %}
    <li {% if id == 0 %} class="active" {% endif %}><a href="{{ url_for('device.view') }}">Add Device</a></li>
    {% for device in devices %}
        <li {% if id == device.id %} class="active" {% endif %}><a href="{{ url_for('device.view', id=device.id) }}">{{ device.name }}</a></li>
    {% endfor %}
{% else %}
    <li style="background-color: #EEEEEE;"><a style="color: #333333;" href="{{ url_for('device.view') }}">Devices</a></li>
    {% for device in devices %}
        <li {% if (not type or type == 'device') and id == device.id %} class="active" {% endif %}><a href="{{ url_for('search.search', q=q, type='device', id=device.id) }}">{{ device.name }}</a></li>
    {% endfor %}
{% endif %}

webui/templates/list_services.html
{% if active != 'search' %}
    <!--<li {% if id == 0 %} class="active" {% endif %}><a href="{{ url_for('service.view') }}">Add Device</a></li>-->
    {% for service in services %}
        <li {% if id == service.id %} class="active" {% endif %}><a href="{{ url_for('service_' ~ service.name ~ '.view', id=service.id) }}">{{ service.name }}</a></li>
    {% endfor %}
{% else %}
    <li style="background-color: #EEEEEE;"><a style="color: #333333;" href="{{ url_for('service.view') }}">Services</a></li>
    {% for service in services %}
        <li {% if (not type or type == 'service') and id == service.id %} class="active" {% endif %}><a href="{{ url_for('search.search', q=q, type='service', id=service.id) }}">{{ service.name }}</a></li>
    {% endfor %}
{% endif %}

webui/templates/list_settings.html
<li{% if category == 'readonly' %} class="active" {% endif %}><a href="{{ url_for('settings.readonly', category='readonly') }}">Read-Only</a></li>
<li{% if category == 'general' %} class="active" {% endif %}><a href="{{ url_for('settings.general', category='general') }}">General</a></li>

webui/templates/list_tokens.html
<li {% if id == 0 %} class="active" {% endif %}><a href="{{ url_for('token.view', id=0) }}">Add Token</a></li>
{% for token in tokens %}
    <li {% if id == token.id %} class="active" {% endif %}><a href="{{ url_for('token.view', id=token.id) }}">{{ token.id }} [{{ token.owner.name}}]</a></li>
{% endfor %}

webui/templates/profile_general.html
{% extends "profile.html" %}
{% block body %}
<h4>{{ user.username }}</h4>
    <form class="change_user_general" action="{{ url_for('user.change', id=user.id) }}" method=post>
        <table class="table table-hover table_general">
            <tr>
                <td>Name</td>
                <td>
                    <input type="text" name="change_user_name" class="form-control" title="Name" value="{{ user.name }}" />
                </td>
            </tr>
            <tr>
                <td>Level</td>
                <td>
                    <input type="text" name="change_user_level" class="form-control" title="Token owner" value="{{ user.level }}" />
                </td>
            </tr>
            <tr>
                <td>Email</td>
                <td>
                    <input type="text" name="change_user_email" class="form-control" title="Token owner" value="{{ user.email }}" />
                </td>
            </tr>
            <tr>
                <td>nethzid</td>
                <td>
                    <input type="text" name="change_user_nethzid" class="form-control" title="Token owner" value="{{ user.nethzid }}" />
                    <input type="text" name="change_user_id" class="invisible" title="" value="{{ user.id }}" />
                </td>
            </tr>

            <tr>
                <td>Welcome Sound</td>
                <td>
                    <select name="change_user_welcome_sound" class="form-control">
                        <option value="">NONE</option>
                        {% for sound in sounds %}
                            <option value="sound['path']" {% if previous['user_welcome_sound'] == sound.path %}selected="selected" {% endif %}>sound['name']</option>
                        {% endfor %}
                    </select>
                </td>
            </tr>
            <tr>
                <td>Creation Date</td>
                <td>{{ user.creation_date }}</td>
            </tr>
            <tr>
                <td>Change?</td>
                <td>
                    <input type="submit" name="change_profile" class="form-control btn-success" title="" value="Change" />
                </td>
            </tr>
        </table>
    </form>
    <table class="table table-hover table_general">
        <tr>
            <td>
                <form class="remove_form" action="{{ url_for('user.remove') }}" method=post>
                    <input type="submit" class="form-control btn-danger" value="Delete Account" />
                    <input name="user_id" class="form-control invisible" title="User id" value="{{ user.id }}" />
                </form>
            </td>
        </tr>
    </table>
{% endblock %}

webui/templates/settings.html
{% extends "layout_admin.html" %}

{% block navi %}
    {% include "list_settings.html" %}
{% endblock %}

{% block body %}
{% endblock %}

webui/templates/settings_readonly.html
{% extends "settings.html" %}
{% block body %}
    <h4>Read-Only</h4>
    <table class="table table-hover table_general">
        <tr>
            <td>WEBUI_TOKEN</td>
            <td>
                {{ webui_token }}
            </td>
        </tr>
        <tr>
            <td>SERVER_TOKEN</td>
            <td>
                {{ server_token }}
            </td>
        </tr>
        <tr>
            <td>API_TOKEN</td>
            <td>
                {{ api_token }}
            </td>
        </tr>
    </table>
{% endblock %}